#!/bin/bash

# Git install.
# Make it as a bash-file!
# bash install.bs

git clone -b 12.0 git@github.com:vertelab/odoo-membership.git
sudo rm /usr/share/odoo-membership -R
sudo mv odoo-membership /usr/share/odoo-membership

# pip install...
for req in `ls /usr/share/odoo*/requirements.txt`
do 
	sudo pip3 install -r $req
done


sudo chown odoo:odoo /usr/share/odoo*/ -R
sudo chmod g+w /usr/share/odoo*/ -R
echo odooaddons
echo odoorestart
echo odootail
