#!/bin/bash

# Git install.
# Make it as a bash-file!
# bash install.bs

odoo-account
odoo-account-extra
odoo-base
odoo-calendar
odoo-crm
odoo-customer-addons
odoo-delivery

odoo-hr
odoo-imagemagick
odoo-knowledge-extra
odoo-l10n_se
odoo-l10n_se_payroll
odoo-marketing
odoo-payroll
odoo-pos
odoo-report
odoo-sale
odoo-stock
odoo-survey
odoo-theme
odoo-user-mail
odoo-website
odoo-website-quote
odoo-website-sale

